baseURL: "" 
title: Helius
theme: PaperMod

enableInlineShortcodes: true
enableRobotsTXT: true
pagination:
  pagerSize: 10

menu:
    main:
        - name: Home
          url: /
          weight: 1
        - name: Papers
          url: papers/
          weight: 2
        - name: Resources
          url: resources/
          weight: 3
        


params:
    author: Akrit Behera
    DateFormat: "January 2006"
    defaultTheme: light
    hideFooter: true
    disableThemeToggle: true
    ShowShareButtons: false
    ShowReadingTime: false
    disableSpecial1stPost: true
    disableAnchoredHeadings: true
    ShowPostNavLinks: false
    ShowBreadCrumbs: false
    ShowCodeCopyButtons: true
    ShowAllPagesInArchive: false
    MainSections: ["papers","resources"]
    ShowToc: false
    disableScrollToTop: false
    TocOpen: true
    ShowWordCount: false
    UseHugoToc: true
    comments: false
    math: true
    profileMode:
          enabled: true
          title: Akrit Behera
          subtitle: "motivated by a deep interest in science and technology. These are my conclusions on a handful of the subjects that truly piqued my interest."
          buttons:
            - name: Papers
              url: papers/
            - name: Resources
              url: resources/


    socialIcons:
        - name: CV
          url: ""
        - name: Email
          url: mailto:akritbehera27@gmail.com
        - name: GitHub
          url: https://github.com/akritbehera27
        - name: Google Scholar
          url: ""

    assets:
        disableScrollBarStyle: true
    cover:
        hiddenInList: false
        hiddenInSingle: true
    label:
      text: "Helius"
      iconHeight: 100

markup:
    goldmark:
        renderer:
            unsafe: true
    highlight:
        guessSyntax: true
        style: autumn 
    tableOfContents:
        endLevel: 2
        ordered: false
        startLevel: 2
